// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValidacaoDeEmail.Models;

namespace ValidacaoDeEmail.Migrations
{
    [DbContext(typeof(TestModelsContext))]
    partial class TestModelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ValidacaoDeEmail.Models.TestModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DateTime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("testDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
